app:
  name: $APP_NAME
  environment: $APP_ENVIRONMENT
  version: $APP_VERSION
  serviceName: $APP_SERVICE_NAME
  serverName: $APP_SERVER_NAME
  debug: $APP_DEBUG
  azureAdminOid: $AZURE_ADMIN_OID
  appUrl: $APP_URL

postgres:
  connectionString: $POSTGRES_CONNECTION_STRING

azureAD:
  enabled: $AZURE_AD_ENABLE
  clientID: $AZURE_AD_CLIENT_ID
  clientSecret: $AZURE_AD_CLIENT_SECRET
  tenantID: $AZURE_AD_CLIENT_TENANT_ID
  redirectUrl: $AZURE_AD_REDIRECT_URL
  scopes: $AZURE_AD_SCOPES
  clientRedirectURL: $AZURE_AD_CLIENT_REDIRECT_URL

azureStorage:
  serviceURL: $AZURE_STORAGE_SERVICE_URL
  accountName: $AZURE_STORAGE_ACCOUNT_NAME
  accountKey: $AZURE_STORAGE_ACCOUNT_KEY
  containerName: $AZURE_STORAGE_CONTAINER_NAME
  maximumFileSizeMB: 10
  sasMaximumHourExpiration: 2

serviceBus:
  connectionString: $SERVICEBUS_CONNECTION_STRING
