// Code generated by ent, DO NOT EDIT.

package emailroleattribute

import (
	"time"
)

const (
	// Label holds the string label denoting the emailroleattribute type in the database.
	Label = "email_role_attribute"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldEmailTemplateID holds the string denoting the email_template_id field in the database.
	FieldEmailTemplateID = "email_template_id"
	// FieldRoleID holds the string denoting the role_id field in the database.
	FieldRoleID = "role_id"
	// EdgeEmailTemplateEdge holds the string denoting the email_template_edge edge name in mutations.
	EdgeEmailTemplateEdge = "email_template_edge"
	// EdgeRoleEdge holds the string denoting the role_edge edge name in mutations.
	EdgeRoleEdge = "role_edge"
	// Table holds the table name of the emailroleattribute in the database.
	Table = "email_role_attributes"
	// EmailTemplateEdgeTable is the table that holds the email_template_edge relation/edge.
	EmailTemplateEdgeTable = "email_role_attributes"
	// EmailTemplateEdgeInverseTable is the table name for the EmailTemplate entity.
	// It exists in this package in order to avoid circular dependency with the "emailtemplate" package.
	EmailTemplateEdgeInverseTable = "email_templates"
	// EmailTemplateEdgeColumn is the table column denoting the email_template_edge relation/edge.
	EmailTemplateEdgeColumn = "email_template_id"
	// RoleEdgeTable is the table that holds the role_edge relation/edge.
	RoleEdgeTable = "email_role_attributes"
	// RoleEdgeInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RoleEdgeInverseTable = "roles"
	// RoleEdgeColumn is the table column denoting the role_edge relation/edge.
	RoleEdgeColumn = "role_id"
)

// Columns holds all SQL columns for emailroleattribute fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldEmailTemplateID,
	FieldRoleID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
