// Code generated by ent, DO NOT EDIT.

package skill

import (
	"time"
)

const (
	// Label holds the string label denoting the skill type in the database.
	Label = "skill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSkillTypeID holds the string denoting the skill_type_id field in the database.
	FieldSkillTypeID = "skill_type_id"
	// EdgeSkillTypeEdge holds the string denoting the skill_type_edge edge name in mutations.
	EdgeSkillTypeEdge = "skill_type_edge"
	// Table holds the table name of the skill in the database.
	Table = "skills"
	// SkillTypeEdgeTable is the table that holds the skill_type_edge relation/edge.
	SkillTypeEdgeTable = "skills"
	// SkillTypeEdgeInverseTable is the table name for the SkillType entity.
	// It exists in this package in order to avoid circular dependency with the "skilltype" package.
	SkillTypeEdgeInverseTable = "skill_types"
	// SkillTypeEdgeColumn is the table column denoting the skill_type_edge relation/edge.
	SkillTypeEdgeColumn = "skill_type_id"
)

// Columns holds all SQL columns for skill fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldDescription,
	FieldSkillTypeID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
)
