// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"trec/ent/audittrail"
	"trec/ent/predicate"
	"trec/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AuditTrailQuery is the builder for querying AuditTrail entities.
type AuditTrailQuery struct {
	config
	limit             *int
	offset            *int
	unique            *bool
	order             []OrderFunc
	fields            []string
	predicates        []predicate.AuditTrail
	withCreatedByEdge *UserQuery
	modifiers         []func(*sql.Selector)
	loadTotal         []func(context.Context, []*AuditTrail) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AuditTrailQuery builder.
func (atq *AuditTrailQuery) Where(ps ...predicate.AuditTrail) *AuditTrailQuery {
	atq.predicates = append(atq.predicates, ps...)
	return atq
}

// Limit adds a limit step to the query.
func (atq *AuditTrailQuery) Limit(limit int) *AuditTrailQuery {
	atq.limit = &limit
	return atq
}

// Offset adds an offset step to the query.
func (atq *AuditTrailQuery) Offset(offset int) *AuditTrailQuery {
	atq.offset = &offset
	return atq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (atq *AuditTrailQuery) Unique(unique bool) *AuditTrailQuery {
	atq.unique = &unique
	return atq
}

// Order adds an order step to the query.
func (atq *AuditTrailQuery) Order(o ...OrderFunc) *AuditTrailQuery {
	atq.order = append(atq.order, o...)
	return atq
}

// QueryCreatedByEdge chains the current query on the "created_by_edge" edge.
func (atq *AuditTrailQuery) QueryCreatedByEdge() *UserQuery {
	query := &UserQuery{config: atq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := atq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := atq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(audittrail.Table, audittrail.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, audittrail.CreatedByEdgeTable, audittrail.CreatedByEdgeColumn),
		)
		fromU = sqlgraph.SetNeighbors(atq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AuditTrail entity from the query.
// Returns a *NotFoundError when no AuditTrail was found.
func (atq *AuditTrailQuery) First(ctx context.Context) (*AuditTrail, error) {
	nodes, err := atq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{audittrail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (atq *AuditTrailQuery) FirstX(ctx context.Context) *AuditTrail {
	node, err := atq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AuditTrail ID from the query.
// Returns a *NotFoundError when no AuditTrail ID was found.
func (atq *AuditTrailQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = atq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{audittrail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (atq *AuditTrailQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := atq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AuditTrail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AuditTrail entity is found.
// Returns a *NotFoundError when no AuditTrail entities are found.
func (atq *AuditTrailQuery) Only(ctx context.Context) (*AuditTrail, error) {
	nodes, err := atq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{audittrail.Label}
	default:
		return nil, &NotSingularError{audittrail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (atq *AuditTrailQuery) OnlyX(ctx context.Context) *AuditTrail {
	node, err := atq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AuditTrail ID in the query.
// Returns a *NotSingularError when more than one AuditTrail ID is found.
// Returns a *NotFoundError when no entities are found.
func (atq *AuditTrailQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = atq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{audittrail.Label}
	default:
		err = &NotSingularError{audittrail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (atq *AuditTrailQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := atq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AuditTrails.
func (atq *AuditTrailQuery) All(ctx context.Context) ([]*AuditTrail, error) {
	if err := atq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return atq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (atq *AuditTrailQuery) AllX(ctx context.Context) []*AuditTrail {
	nodes, err := atq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AuditTrail IDs.
func (atq *AuditTrailQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := atq.Select(audittrail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (atq *AuditTrailQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := atq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (atq *AuditTrailQuery) Count(ctx context.Context) (int, error) {
	if err := atq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return atq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (atq *AuditTrailQuery) CountX(ctx context.Context) int {
	count, err := atq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (atq *AuditTrailQuery) Exist(ctx context.Context) (bool, error) {
	if err := atq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return atq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (atq *AuditTrailQuery) ExistX(ctx context.Context) bool {
	exist, err := atq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AuditTrailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (atq *AuditTrailQuery) Clone() *AuditTrailQuery {
	if atq == nil {
		return nil
	}
	return &AuditTrailQuery{
		config:            atq.config,
		limit:             atq.limit,
		offset:            atq.offset,
		order:             append([]OrderFunc{}, atq.order...),
		predicates:        append([]predicate.AuditTrail{}, atq.predicates...),
		withCreatedByEdge: atq.withCreatedByEdge.Clone(),
		// clone intermediate query.
		sql:    atq.sql.Clone(),
		path:   atq.path,
		unique: atq.unique,
	}
}

// WithCreatedByEdge tells the query-builder to eager-load the nodes that are connected to
// the "created_by_edge" edge. The optional arguments are used to configure the query builder of the edge.
func (atq *AuditTrailQuery) WithCreatedByEdge(opts ...func(*UserQuery)) *AuditTrailQuery {
	query := &UserQuery{config: atq.config}
	for _, opt := range opts {
		opt(query)
	}
	atq.withCreatedByEdge = query
	return atq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedBy uuid.UUID `json:"created_by,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AuditTrail.Query().
//		GroupBy(audittrail.FieldCreatedBy).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (atq *AuditTrailQuery) GroupBy(field string, fields ...string) *AuditTrailGroupBy {
	grbuild := &AuditTrailGroupBy{config: atq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := atq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return atq.sqlQuery(ctx), nil
	}
	grbuild.label = audittrail.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedBy uuid.UUID `json:"created_by,omitempty"`
//	}
//
//	client.AuditTrail.Query().
//		Select(audittrail.FieldCreatedBy).
//		Scan(ctx, &v)
func (atq *AuditTrailQuery) Select(fields ...string) *AuditTrailSelect {
	atq.fields = append(atq.fields, fields...)
	selbuild := &AuditTrailSelect{AuditTrailQuery: atq}
	selbuild.label = audittrail.Label
	selbuild.flds, selbuild.scan = &atq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a AuditTrailSelect configured with the given aggregations.
func (atq *AuditTrailQuery) Aggregate(fns ...AggregateFunc) *AuditTrailSelect {
	return atq.Select().Aggregate(fns...)
}

func (atq *AuditTrailQuery) prepareQuery(ctx context.Context) error {
	for _, f := range atq.fields {
		if !audittrail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if atq.path != nil {
		prev, err := atq.path(ctx)
		if err != nil {
			return err
		}
		atq.sql = prev
	}
	return nil
}

func (atq *AuditTrailQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AuditTrail, error) {
	var (
		nodes       = []*AuditTrail{}
		_spec       = atq.querySpec()
		loadedTypes = [1]bool{
			atq.withCreatedByEdge != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AuditTrail).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AuditTrail{config: atq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(atq.modifiers) > 0 {
		_spec.Modifiers = atq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, atq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := atq.withCreatedByEdge; query != nil {
		if err := atq.loadCreatedByEdge(ctx, query, nodes, nil,
			func(n *AuditTrail, e *User) { n.Edges.CreatedByEdge = e }); err != nil {
			return nil, err
		}
	}
	for i := range atq.loadTotal {
		if err := atq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (atq *AuditTrailQuery) loadCreatedByEdge(ctx context.Context, query *UserQuery, nodes []*AuditTrail, init func(*AuditTrail), assign func(*AuditTrail, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AuditTrail)
	for i := range nodes {
		fk := nodes[i].CreatedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "created_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (atq *AuditTrailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := atq.querySpec()
	if len(atq.modifiers) > 0 {
		_spec.Modifiers = atq.modifiers
	}
	_spec.Node.Columns = atq.fields
	if len(atq.fields) > 0 {
		_spec.Unique = atq.unique != nil && *atq.unique
	}
	return sqlgraph.CountNodes(ctx, atq.driver, _spec)
}

func (atq *AuditTrailQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := atq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (atq *AuditTrailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   audittrail.Table,
			Columns: audittrail.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: audittrail.FieldID,
			},
		},
		From:   atq.sql,
		Unique: true,
	}
	if unique := atq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := atq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, audittrail.FieldID)
		for i := range fields {
			if fields[i] != audittrail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := atq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := atq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := atq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := atq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (atq *AuditTrailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(atq.driver.Dialect())
	t1 := builder.Table(audittrail.Table)
	columns := atq.fields
	if len(columns) == 0 {
		columns = audittrail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if atq.sql != nil {
		selector = atq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if atq.unique != nil && *atq.unique {
		selector.Distinct()
	}
	for _, p := range atq.predicates {
		p(selector)
	}
	for _, p := range atq.order {
		p(selector)
	}
	if offset := atq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := atq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AuditTrailGroupBy is the group-by builder for AuditTrail entities.
type AuditTrailGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (atgb *AuditTrailGroupBy) Aggregate(fns ...AggregateFunc) *AuditTrailGroupBy {
	atgb.fns = append(atgb.fns, fns...)
	return atgb
}

// Scan applies the group-by query and scans the result into the given value.
func (atgb *AuditTrailGroupBy) Scan(ctx context.Context, v any) error {
	query, err := atgb.path(ctx)
	if err != nil {
		return err
	}
	atgb.sql = query
	return atgb.sqlScan(ctx, v)
}

func (atgb *AuditTrailGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range atgb.fields {
		if !audittrail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := atgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := atgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (atgb *AuditTrailGroupBy) sqlQuery() *sql.Selector {
	selector := atgb.sql.Select()
	aggregation := make([]string, 0, len(atgb.fns))
	for _, fn := range atgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(atgb.fields)+len(atgb.fns))
		for _, f := range atgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(atgb.fields...)...)
}

// AuditTrailSelect is the builder for selecting fields of AuditTrail entities.
type AuditTrailSelect struct {
	*AuditTrailQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ats *AuditTrailSelect) Aggregate(fns ...AggregateFunc) *AuditTrailSelect {
	ats.fns = append(ats.fns, fns...)
	return ats
}

// Scan applies the selector query and scans the result into the given value.
func (ats *AuditTrailSelect) Scan(ctx context.Context, v any) error {
	if err := ats.prepareQuery(ctx); err != nil {
		return err
	}
	ats.sql = ats.AuditTrailQuery.sqlQuery(ctx)
	return ats.sqlScan(ctx, v)
}

func (ats *AuditTrailSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(ats.fns))
	for _, fn := range ats.fns {
		aggregation = append(aggregation, fn(ats.sql))
	}
	switch n := len(*ats.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		ats.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		ats.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := ats.sql.Query()
	if err := ats.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
