// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"trec/ent/attachment"
	"trec/ent/candidate"
	"trec/ent/candidateeducate"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CandidateEducateCreate is the builder for creating a CandidateEducate entity.
type CandidateEducateCreate struct {
	config
	mutation *CandidateEducateMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (cec *CandidateEducateCreate) SetCreatedAt(t time.Time) *CandidateEducateCreate {
	cec.mutation.SetCreatedAt(t)
	return cec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cec *CandidateEducateCreate) SetNillableCreatedAt(t *time.Time) *CandidateEducateCreate {
	if t != nil {
		cec.SetCreatedAt(*t)
	}
	return cec
}

// SetUpdatedAt sets the "updated_at" field.
func (cec *CandidateEducateCreate) SetUpdatedAt(t time.Time) *CandidateEducateCreate {
	cec.mutation.SetUpdatedAt(t)
	return cec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cec *CandidateEducateCreate) SetNillableUpdatedAt(t *time.Time) *CandidateEducateCreate {
	if t != nil {
		cec.SetUpdatedAt(*t)
	}
	return cec
}

// SetDeletedAt sets the "deleted_at" field.
func (cec *CandidateEducateCreate) SetDeletedAt(t time.Time) *CandidateEducateCreate {
	cec.mutation.SetDeletedAt(t)
	return cec
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (cec *CandidateEducateCreate) SetNillableDeletedAt(t *time.Time) *CandidateEducateCreate {
	if t != nil {
		cec.SetDeletedAt(*t)
	}
	return cec
}

// SetCandidateID sets the "candidate_id" field.
func (cec *CandidateEducateCreate) SetCandidateID(u uuid.UUID) *CandidateEducateCreate {
	cec.mutation.SetCandidateID(u)
	return cec
}

// SetNillableCandidateID sets the "candidate_id" field if the given value is not nil.
func (cec *CandidateEducateCreate) SetNillableCandidateID(u *uuid.UUID) *CandidateEducateCreate {
	if u != nil {
		cec.SetCandidateID(*u)
	}
	return cec
}

// SetSchoolName sets the "school_name" field.
func (cec *CandidateEducateCreate) SetSchoolName(s string) *CandidateEducateCreate {
	cec.mutation.SetSchoolName(s)
	return cec
}

// SetMajor sets the "major" field.
func (cec *CandidateEducateCreate) SetMajor(s string) *CandidateEducateCreate {
	cec.mutation.SetMajor(s)
	return cec
}

// SetNillableMajor sets the "major" field if the given value is not nil.
func (cec *CandidateEducateCreate) SetNillableMajor(s *string) *CandidateEducateCreate {
	if s != nil {
		cec.SetMajor(*s)
	}
	return cec
}

// SetGpa sets the "gpa" field.
func (cec *CandidateEducateCreate) SetGpa(s string) *CandidateEducateCreate {
	cec.mutation.SetGpa(s)
	return cec
}

// SetNillableGpa sets the "gpa" field if the given value is not nil.
func (cec *CandidateEducateCreate) SetNillableGpa(s *string) *CandidateEducateCreate {
	if s != nil {
		cec.SetGpa(*s)
	}
	return cec
}

// SetLocation sets the "location" field.
func (cec *CandidateEducateCreate) SetLocation(s string) *CandidateEducateCreate {
	cec.mutation.SetLocation(s)
	return cec
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (cec *CandidateEducateCreate) SetNillableLocation(s *string) *CandidateEducateCreate {
	if s != nil {
		cec.SetLocation(*s)
	}
	return cec
}

// SetDescription sets the "description" field.
func (cec *CandidateEducateCreate) SetDescription(s string) *CandidateEducateCreate {
	cec.mutation.SetDescription(s)
	return cec
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (cec *CandidateEducateCreate) SetNillableDescription(s *string) *CandidateEducateCreate {
	if s != nil {
		cec.SetDescription(*s)
	}
	return cec
}

// SetStartDate sets the "start_date" field.
func (cec *CandidateEducateCreate) SetStartDate(t time.Time) *CandidateEducateCreate {
	cec.mutation.SetStartDate(t)
	return cec
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (cec *CandidateEducateCreate) SetNillableStartDate(t *time.Time) *CandidateEducateCreate {
	if t != nil {
		cec.SetStartDate(*t)
	}
	return cec
}

// SetEndDate sets the "end_date" field.
func (cec *CandidateEducateCreate) SetEndDate(t time.Time) *CandidateEducateCreate {
	cec.mutation.SetEndDate(t)
	return cec
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (cec *CandidateEducateCreate) SetNillableEndDate(t *time.Time) *CandidateEducateCreate {
	if t != nil {
		cec.SetEndDate(*t)
	}
	return cec
}

// SetID sets the "id" field.
func (cec *CandidateEducateCreate) SetID(u uuid.UUID) *CandidateEducateCreate {
	cec.mutation.SetID(u)
	return cec
}

// AddAttachmentEdgeIDs adds the "attachment_edges" edge to the Attachment entity by IDs.
func (cec *CandidateEducateCreate) AddAttachmentEdgeIDs(ids ...uuid.UUID) *CandidateEducateCreate {
	cec.mutation.AddAttachmentEdgeIDs(ids...)
	return cec
}

// AddAttachmentEdges adds the "attachment_edges" edges to the Attachment entity.
func (cec *CandidateEducateCreate) AddAttachmentEdges(a ...*Attachment) *CandidateEducateCreate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cec.AddAttachmentEdgeIDs(ids...)
}

// SetCandidateEdgeID sets the "candidate_edge" edge to the Candidate entity by ID.
func (cec *CandidateEducateCreate) SetCandidateEdgeID(id uuid.UUID) *CandidateEducateCreate {
	cec.mutation.SetCandidateEdgeID(id)
	return cec
}

// SetNillableCandidateEdgeID sets the "candidate_edge" edge to the Candidate entity by ID if the given value is not nil.
func (cec *CandidateEducateCreate) SetNillableCandidateEdgeID(id *uuid.UUID) *CandidateEducateCreate {
	if id != nil {
		cec = cec.SetCandidateEdgeID(*id)
	}
	return cec
}

// SetCandidateEdge sets the "candidate_edge" edge to the Candidate entity.
func (cec *CandidateEducateCreate) SetCandidateEdge(c *Candidate) *CandidateEducateCreate {
	return cec.SetCandidateEdgeID(c.ID)
}

// Mutation returns the CandidateEducateMutation object of the builder.
func (cec *CandidateEducateCreate) Mutation() *CandidateEducateMutation {
	return cec.mutation
}

// Save creates the CandidateEducate in the database.
func (cec *CandidateEducateCreate) Save(ctx context.Context) (*CandidateEducate, error) {
	var (
		err  error
		node *CandidateEducate
	)
	cec.defaults()
	if len(cec.hooks) == 0 {
		if err = cec.check(); err != nil {
			return nil, err
		}
		node, err = cec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CandidateEducateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cec.check(); err != nil {
				return nil, err
			}
			cec.mutation = mutation
			if node, err = cec.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cec.hooks) - 1; i >= 0; i-- {
			if cec.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cec.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cec.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*CandidateEducate)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CandidateEducateMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cec *CandidateEducateCreate) SaveX(ctx context.Context) *CandidateEducate {
	v, err := cec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cec *CandidateEducateCreate) Exec(ctx context.Context) error {
	_, err := cec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cec *CandidateEducateCreate) ExecX(ctx context.Context) {
	if err := cec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cec *CandidateEducateCreate) defaults() {
	if _, ok := cec.mutation.CreatedAt(); !ok {
		v := candidateeducate.DefaultCreatedAt()
		cec.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cec *CandidateEducateCreate) check() error {
	if _, ok := cec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CandidateEducate.created_at"`)}
	}
	if _, ok := cec.mutation.SchoolName(); !ok {
		return &ValidationError{Name: "school_name", err: errors.New(`ent: missing required field "CandidateEducate.school_name"`)}
	}
	if v, ok := cec.mutation.SchoolName(); ok {
		if err := candidateeducate.SchoolNameValidator(v); err != nil {
			return &ValidationError{Name: "school_name", err: fmt.Errorf(`ent: validator failed for field "CandidateEducate.school_name": %w`, err)}
		}
	}
	if v, ok := cec.mutation.Major(); ok {
		if err := candidateeducate.MajorValidator(v); err != nil {
			return &ValidationError{Name: "major", err: fmt.Errorf(`ent: validator failed for field "CandidateEducate.major": %w`, err)}
		}
	}
	if v, ok := cec.mutation.Gpa(); ok {
		if err := candidateeducate.GpaValidator(v); err != nil {
			return &ValidationError{Name: "gpa", err: fmt.Errorf(`ent: validator failed for field "CandidateEducate.gpa": %w`, err)}
		}
	}
	if v, ok := cec.mutation.Location(); ok {
		if err := candidateeducate.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "CandidateEducate.location": %w`, err)}
		}
	}
	if v, ok := cec.mutation.Description(); ok {
		if err := candidateeducate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "CandidateEducate.description": %w`, err)}
		}
	}
	return nil
}

func (cec *CandidateEducateCreate) sqlSave(ctx context.Context) (*CandidateEducate, error) {
	_node, _spec := cec.createSpec()
	if err := sqlgraph.CreateNode(ctx, cec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (cec *CandidateEducateCreate) createSpec() (*CandidateEducate, *sqlgraph.CreateSpec) {
	var (
		_node = &CandidateEducate{config: cec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: candidateeducate.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: candidateeducate.FieldID,
			},
		}
	)
	if id, ok := cec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cec.mutation.CreatedAt(); ok {
		_spec.SetField(candidateeducate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cec.mutation.UpdatedAt(); ok {
		_spec.SetField(candidateeducate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cec.mutation.DeletedAt(); ok {
		_spec.SetField(candidateeducate.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := cec.mutation.SchoolName(); ok {
		_spec.SetField(candidateeducate.FieldSchoolName, field.TypeString, value)
		_node.SchoolName = value
	}
	if value, ok := cec.mutation.Major(); ok {
		_spec.SetField(candidateeducate.FieldMajor, field.TypeString, value)
		_node.Major = value
	}
	if value, ok := cec.mutation.Gpa(); ok {
		_spec.SetField(candidateeducate.FieldGpa, field.TypeString, value)
		_node.Gpa = value
	}
	if value, ok := cec.mutation.Location(); ok {
		_spec.SetField(candidateeducate.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := cec.mutation.Description(); ok {
		_spec.SetField(candidateeducate.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := cec.mutation.StartDate(); ok {
		_spec.SetField(candidateeducate.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := cec.mutation.EndDate(); ok {
		_spec.SetField(candidateeducate.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if nodes := cec.mutation.AttachmentEdgesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   candidateeducate.AttachmentEdgesTable,
			Columns: []string{candidateeducate.AttachmentEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: attachment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cec.mutation.CandidateEdgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   candidateeducate.CandidateEdgeTable,
			Columns: []string{candidateeducate.CandidateEdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: candidate.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CandidateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CandidateEducateCreateBulk is the builder for creating many CandidateEducate entities in bulk.
type CandidateEducateCreateBulk struct {
	config
	builders []*CandidateEducateCreate
}

// Save creates the CandidateEducate entities in the database.
func (cecb *CandidateEducateCreateBulk) Save(ctx context.Context) ([]*CandidateEducate, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cecb.builders))
	nodes := make([]*CandidateEducate, len(cecb.builders))
	mutators := make([]Mutator, len(cecb.builders))
	for i := range cecb.builders {
		func(i int, root context.Context) {
			builder := cecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CandidateEducateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cecb *CandidateEducateCreateBulk) SaveX(ctx context.Context) []*CandidateEducate {
	v, err := cecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cecb *CandidateEducateCreateBulk) Exec(ctx context.Context) error {
	_, err := cecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cecb *CandidateEducateCreateBulk) ExecX(ctx context.Context) {
	if err := cecb.Exec(ctx); err != nil {
		panic(err)
	}
}
