// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"trec/ent/hiringjob"
	"trec/ent/hiringjobstep"
	"trec/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// HiringJobStepCreate is the builder for creating a HiringJobStep entity.
type HiringJobStepCreate struct {
	config
	mutation *HiringJobStepMutation
	hooks    []Hook
}

// SetHiringJobID sets the "hiring_job_id" field.
func (hjsc *HiringJobStepCreate) SetHiringJobID(u uuid.UUID) *HiringJobStepCreate {
	hjsc.mutation.SetHiringJobID(u)
	return hjsc
}

// SetNillableHiringJobID sets the "hiring_job_id" field if the given value is not nil.
func (hjsc *HiringJobStepCreate) SetNillableHiringJobID(u *uuid.UUID) *HiringJobStepCreate {
	if u != nil {
		hjsc.SetHiringJobID(*u)
	}
	return hjsc
}

// SetType sets the "type" field.
func (hjsc *HiringJobStepCreate) SetType(h hiringjobstep.Type) *HiringJobStepCreate {
	hjsc.mutation.SetType(h)
	return hjsc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (hjsc *HiringJobStepCreate) SetNillableType(h *hiringjobstep.Type) *HiringJobStepCreate {
	if h != nil {
		hjsc.SetType(*h)
	}
	return hjsc
}

// SetCreatedAt sets the "created_at" field.
func (hjsc *HiringJobStepCreate) SetCreatedAt(t time.Time) *HiringJobStepCreate {
	hjsc.mutation.SetCreatedAt(t)
	return hjsc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (hjsc *HiringJobStepCreate) SetNillableCreatedAt(t *time.Time) *HiringJobStepCreate {
	if t != nil {
		hjsc.SetCreatedAt(*t)
	}
	return hjsc
}

// SetUpdatedAt sets the "updated_at" field.
func (hjsc *HiringJobStepCreate) SetUpdatedAt(t time.Time) *HiringJobStepCreate {
	hjsc.mutation.SetUpdatedAt(t)
	return hjsc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (hjsc *HiringJobStepCreate) SetNillableUpdatedAt(t *time.Time) *HiringJobStepCreate {
	if t != nil {
		hjsc.SetUpdatedAt(*t)
	}
	return hjsc
}

// SetCreatedByID sets the "created_by_id" field.
func (hjsc *HiringJobStepCreate) SetCreatedByID(u uuid.UUID) *HiringJobStepCreate {
	hjsc.mutation.SetCreatedByID(u)
	return hjsc
}

// SetNillableCreatedByID sets the "created_by_id" field if the given value is not nil.
func (hjsc *HiringJobStepCreate) SetNillableCreatedByID(u *uuid.UUID) *HiringJobStepCreate {
	if u != nil {
		hjsc.SetCreatedByID(*u)
	}
	return hjsc
}

// SetID sets the "id" field.
func (hjsc *HiringJobStepCreate) SetID(u uuid.UUID) *HiringJobStepCreate {
	hjsc.mutation.SetID(u)
	return hjsc
}

// SetHiringJobEdgeID sets the "hiring_job_edge" edge to the HiringJob entity by ID.
func (hjsc *HiringJobStepCreate) SetHiringJobEdgeID(id uuid.UUID) *HiringJobStepCreate {
	hjsc.mutation.SetHiringJobEdgeID(id)
	return hjsc
}

// SetNillableHiringJobEdgeID sets the "hiring_job_edge" edge to the HiringJob entity by ID if the given value is not nil.
func (hjsc *HiringJobStepCreate) SetNillableHiringJobEdgeID(id *uuid.UUID) *HiringJobStepCreate {
	if id != nil {
		hjsc = hjsc.SetHiringJobEdgeID(*id)
	}
	return hjsc
}

// SetHiringJobEdge sets the "hiring_job_edge" edge to the HiringJob entity.
func (hjsc *HiringJobStepCreate) SetHiringJobEdge(h *HiringJob) *HiringJobStepCreate {
	return hjsc.SetHiringJobEdgeID(h.ID)
}

// SetCreatedByEdgeID sets the "created_by_edge" edge to the User entity by ID.
func (hjsc *HiringJobStepCreate) SetCreatedByEdgeID(id uuid.UUID) *HiringJobStepCreate {
	hjsc.mutation.SetCreatedByEdgeID(id)
	return hjsc
}

// SetNillableCreatedByEdgeID sets the "created_by_edge" edge to the User entity by ID if the given value is not nil.
func (hjsc *HiringJobStepCreate) SetNillableCreatedByEdgeID(id *uuid.UUID) *HiringJobStepCreate {
	if id != nil {
		hjsc = hjsc.SetCreatedByEdgeID(*id)
	}
	return hjsc
}

// SetCreatedByEdge sets the "created_by_edge" edge to the User entity.
func (hjsc *HiringJobStepCreate) SetCreatedByEdge(u *User) *HiringJobStepCreate {
	return hjsc.SetCreatedByEdgeID(u.ID)
}

// Mutation returns the HiringJobStepMutation object of the builder.
func (hjsc *HiringJobStepCreate) Mutation() *HiringJobStepMutation {
	return hjsc.mutation
}

// Save creates the HiringJobStep in the database.
func (hjsc *HiringJobStepCreate) Save(ctx context.Context) (*HiringJobStep, error) {
	var (
		err  error
		node *HiringJobStep
	)
	hjsc.defaults()
	if len(hjsc.hooks) == 0 {
		if err = hjsc.check(); err != nil {
			return nil, err
		}
		node, err = hjsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HiringJobStepMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = hjsc.check(); err != nil {
				return nil, err
			}
			hjsc.mutation = mutation
			if node, err = hjsc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(hjsc.hooks) - 1; i >= 0; i-- {
			if hjsc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = hjsc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, hjsc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*HiringJobStep)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from HiringJobStepMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (hjsc *HiringJobStepCreate) SaveX(ctx context.Context) *HiringJobStep {
	v, err := hjsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hjsc *HiringJobStepCreate) Exec(ctx context.Context) error {
	_, err := hjsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hjsc *HiringJobStepCreate) ExecX(ctx context.Context) {
	if err := hjsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hjsc *HiringJobStepCreate) defaults() {
	if _, ok := hjsc.mutation.GetType(); !ok {
		v := hiringjobstep.DefaultType
		hjsc.mutation.SetType(v)
	}
	if _, ok := hjsc.mutation.CreatedAt(); !ok {
		v := hiringjobstep.DefaultCreatedAt()
		hjsc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hjsc *HiringJobStepCreate) check() error {
	if _, ok := hjsc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "HiringJobStep.type"`)}
	}
	if v, ok := hjsc.mutation.GetType(); ok {
		if err := hiringjobstep.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "HiringJobStep.type": %w`, err)}
		}
	}
	if _, ok := hjsc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HiringJobStep.created_at"`)}
	}
	return nil
}

func (hjsc *HiringJobStepCreate) sqlSave(ctx context.Context) (*HiringJobStep, error) {
	_node, _spec := hjsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hjsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (hjsc *HiringJobStepCreate) createSpec() (*HiringJobStep, *sqlgraph.CreateSpec) {
	var (
		_node = &HiringJobStep{config: hjsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: hiringjobstep.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: hiringjobstep.FieldID,
			},
		}
	)
	if id, ok := hjsc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := hjsc.mutation.GetType(); ok {
		_spec.SetField(hiringjobstep.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := hjsc.mutation.CreatedAt(); ok {
		_spec.SetField(hiringjobstep.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := hjsc.mutation.UpdatedAt(); ok {
		_spec.SetField(hiringjobstep.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := hjsc.mutation.HiringJobEdgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hiringjobstep.HiringJobEdgeTable,
			Columns: []string{hiringjobstep.HiringJobEdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: hiringjob.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HiringJobID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := hjsc.mutation.CreatedByEdgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hiringjobstep.CreatedByEdgeTable,
			Columns: []string{hiringjobstep.CreatedByEdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedByID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HiringJobStepCreateBulk is the builder for creating many HiringJobStep entities in bulk.
type HiringJobStepCreateBulk struct {
	config
	builders []*HiringJobStepCreate
}

// Save creates the HiringJobStep entities in the database.
func (hjscb *HiringJobStepCreateBulk) Save(ctx context.Context) ([]*HiringJobStep, error) {
	specs := make([]*sqlgraph.CreateSpec, len(hjscb.builders))
	nodes := make([]*HiringJobStep, len(hjscb.builders))
	mutators := make([]Mutator, len(hjscb.builders))
	for i := range hjscb.builders {
		func(i int, root context.Context) {
			builder := hjscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HiringJobStepMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hjscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hjscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hjscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hjscb *HiringJobStepCreateBulk) SaveX(ctx context.Context) []*HiringJobStep {
	v, err := hjscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hjscb *HiringJobStepCreateBulk) Exec(ctx context.Context) error {
	_, err := hjscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hjscb *HiringJobStepCreateBulk) ExecX(ctx context.Context) {
	if err := hjscb.Exec(ctx); err != nil {
		panic(err)
	}
}
