// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"trec/ent/predicate"
	"trec/ent/role"
	"trec/ent/user"
	"trec/ent/userrole"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserRoleUpdate is the builder for updating UserRole entities.
type UserRoleUpdate struct {
	config
	hooks    []Hook
	mutation *UserRoleMutation
}

// Where appends a list predicates to the UserRoleUpdate builder.
func (uru *UserRoleUpdate) Where(ps ...predicate.UserRole) *UserRoleUpdate {
	uru.mutation.Where(ps...)
	return uru
}

// SetUpdatedAt sets the "updated_at" field.
func (uru *UserRoleUpdate) SetUpdatedAt(t time.Time) *UserRoleUpdate {
	uru.mutation.SetUpdatedAt(t)
	return uru
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableUpdatedAt(t *time.Time) *UserRoleUpdate {
	if t != nil {
		uru.SetUpdatedAt(*t)
	}
	return uru
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (uru *UserRoleUpdate) ClearUpdatedAt() *UserRoleUpdate {
	uru.mutation.ClearUpdatedAt()
	return uru
}

// SetDeletedAt sets the "deleted_at" field.
func (uru *UserRoleUpdate) SetDeletedAt(t time.Time) *UserRoleUpdate {
	uru.mutation.SetDeletedAt(t)
	return uru
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableDeletedAt(t *time.Time) *UserRoleUpdate {
	if t != nil {
		uru.SetDeletedAt(*t)
	}
	return uru
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (uru *UserRoleUpdate) ClearDeletedAt() *UserRoleUpdate {
	uru.mutation.ClearDeletedAt()
	return uru
}

// SetRoleID sets the "role_id" field.
func (uru *UserRoleUpdate) SetRoleID(u uuid.UUID) *UserRoleUpdate {
	uru.mutation.SetRoleID(u)
	return uru
}

// SetUserID sets the "user_id" field.
func (uru *UserRoleUpdate) SetUserID(u uuid.UUID) *UserRoleUpdate {
	uru.mutation.SetUserID(u)
	return uru
}

// SetUserEdgeID sets the "user_edge" edge to the User entity by ID.
func (uru *UserRoleUpdate) SetUserEdgeID(id uuid.UUID) *UserRoleUpdate {
	uru.mutation.SetUserEdgeID(id)
	return uru
}

// SetUserEdge sets the "user_edge" edge to the User entity.
func (uru *UserRoleUpdate) SetUserEdge(u *User) *UserRoleUpdate {
	return uru.SetUserEdgeID(u.ID)
}

// SetRoleEdgeID sets the "role_edge" edge to the Role entity by ID.
func (uru *UserRoleUpdate) SetRoleEdgeID(id uuid.UUID) *UserRoleUpdate {
	uru.mutation.SetRoleEdgeID(id)
	return uru
}

// SetRoleEdge sets the "role_edge" edge to the Role entity.
func (uru *UserRoleUpdate) SetRoleEdge(r *Role) *UserRoleUpdate {
	return uru.SetRoleEdgeID(r.ID)
}

// Mutation returns the UserRoleMutation object of the builder.
func (uru *UserRoleUpdate) Mutation() *UserRoleMutation {
	return uru.mutation
}

// ClearUserEdge clears the "user_edge" edge to the User entity.
func (uru *UserRoleUpdate) ClearUserEdge() *UserRoleUpdate {
	uru.mutation.ClearUserEdge()
	return uru
}

// ClearRoleEdge clears the "role_edge" edge to the Role entity.
func (uru *UserRoleUpdate) ClearRoleEdge() *UserRoleUpdate {
	uru.mutation.ClearRoleEdge()
	return uru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uru *UserRoleUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uru.hooks) == 0 {
		if err = uru.check(); err != nil {
			return 0, err
		}
		affected, err = uru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserRoleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uru.check(); err != nil {
				return 0, err
			}
			uru.mutation = mutation
			affected, err = uru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uru.hooks) - 1; i >= 0; i-- {
			if uru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (uru *UserRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := uru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uru *UserRoleUpdate) Exec(ctx context.Context) error {
	_, err := uru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uru *UserRoleUpdate) ExecX(ctx context.Context) {
	if err := uru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uru *UserRoleUpdate) check() error {
	if _, ok := uru.mutation.UserEdgeID(); uru.mutation.UserEdgeCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserRole.user_edge"`)
	}
	if _, ok := uru.mutation.RoleEdgeID(); uru.mutation.RoleEdgeCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserRole.role_edge"`)
	}
	return nil
}

func (uru *UserRoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userrole.Table,
			Columns: userrole.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: userrole.FieldID,
			},
		},
	}
	if ps := uru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uru.mutation.UpdatedAt(); ok {
		_spec.SetField(userrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if uru.mutation.UpdatedAtCleared() {
		_spec.ClearField(userrole.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := uru.mutation.DeletedAt(); ok {
		_spec.SetField(userrole.FieldDeletedAt, field.TypeTime, value)
	}
	if uru.mutation.DeletedAtCleared() {
		_spec.ClearField(userrole.FieldDeletedAt, field.TypeTime)
	}
	if uru.mutation.UserEdgeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserEdgeTable,
			Columns: []string{userrole.UserEdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uru.mutation.UserEdgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserEdgeTable,
			Columns: []string{userrole.UserEdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uru.mutation.RoleEdgeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleEdgeTable,
			Columns: []string{userrole.RoleEdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: role.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uru.mutation.RoleEdgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleEdgeTable,
			Columns: []string{userrole.RoleEdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: role.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// UserRoleUpdateOne is the builder for updating a single UserRole entity.
type UserRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserRoleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (uruo *UserRoleUpdateOne) SetUpdatedAt(t time.Time) *UserRoleUpdateOne {
	uruo.mutation.SetUpdatedAt(t)
	return uruo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableUpdatedAt(t *time.Time) *UserRoleUpdateOne {
	if t != nil {
		uruo.SetUpdatedAt(*t)
	}
	return uruo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (uruo *UserRoleUpdateOne) ClearUpdatedAt() *UserRoleUpdateOne {
	uruo.mutation.ClearUpdatedAt()
	return uruo
}

// SetDeletedAt sets the "deleted_at" field.
func (uruo *UserRoleUpdateOne) SetDeletedAt(t time.Time) *UserRoleUpdateOne {
	uruo.mutation.SetDeletedAt(t)
	return uruo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableDeletedAt(t *time.Time) *UserRoleUpdateOne {
	if t != nil {
		uruo.SetDeletedAt(*t)
	}
	return uruo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (uruo *UserRoleUpdateOne) ClearDeletedAt() *UserRoleUpdateOne {
	uruo.mutation.ClearDeletedAt()
	return uruo
}

// SetRoleID sets the "role_id" field.
func (uruo *UserRoleUpdateOne) SetRoleID(u uuid.UUID) *UserRoleUpdateOne {
	uruo.mutation.SetRoleID(u)
	return uruo
}

// SetUserID sets the "user_id" field.
func (uruo *UserRoleUpdateOne) SetUserID(u uuid.UUID) *UserRoleUpdateOne {
	uruo.mutation.SetUserID(u)
	return uruo
}

// SetUserEdgeID sets the "user_edge" edge to the User entity by ID.
func (uruo *UserRoleUpdateOne) SetUserEdgeID(id uuid.UUID) *UserRoleUpdateOne {
	uruo.mutation.SetUserEdgeID(id)
	return uruo
}

// SetUserEdge sets the "user_edge" edge to the User entity.
func (uruo *UserRoleUpdateOne) SetUserEdge(u *User) *UserRoleUpdateOne {
	return uruo.SetUserEdgeID(u.ID)
}

// SetRoleEdgeID sets the "role_edge" edge to the Role entity by ID.
func (uruo *UserRoleUpdateOne) SetRoleEdgeID(id uuid.UUID) *UserRoleUpdateOne {
	uruo.mutation.SetRoleEdgeID(id)
	return uruo
}

// SetRoleEdge sets the "role_edge" edge to the Role entity.
func (uruo *UserRoleUpdateOne) SetRoleEdge(r *Role) *UserRoleUpdateOne {
	return uruo.SetRoleEdgeID(r.ID)
}

// Mutation returns the UserRoleMutation object of the builder.
func (uruo *UserRoleUpdateOne) Mutation() *UserRoleMutation {
	return uruo.mutation
}

// ClearUserEdge clears the "user_edge" edge to the User entity.
func (uruo *UserRoleUpdateOne) ClearUserEdge() *UserRoleUpdateOne {
	uruo.mutation.ClearUserEdge()
	return uruo
}

// ClearRoleEdge clears the "role_edge" edge to the Role entity.
func (uruo *UserRoleUpdateOne) ClearRoleEdge() *UserRoleUpdateOne {
	uruo.mutation.ClearRoleEdge()
	return uruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uruo *UserRoleUpdateOne) Select(field string, fields ...string) *UserRoleUpdateOne {
	uruo.fields = append([]string{field}, fields...)
	return uruo
}

// Save executes the query and returns the updated UserRole entity.
func (uruo *UserRoleUpdateOne) Save(ctx context.Context) (*UserRole, error) {
	var (
		err  error
		node *UserRole
	)
	if len(uruo.hooks) == 0 {
		if err = uruo.check(); err != nil {
			return nil, err
		}
		node, err = uruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserRoleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uruo.check(); err != nil {
				return nil, err
			}
			uruo.mutation = mutation
			node, err = uruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uruo.hooks) - 1; i >= 0; i-- {
			if uruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uruo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, uruo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*UserRole)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from UserRoleMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uruo *UserRoleUpdateOne) SaveX(ctx context.Context) *UserRole {
	node, err := uruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uruo *UserRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := uruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uruo *UserRoleUpdateOne) ExecX(ctx context.Context) {
	if err := uruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uruo *UserRoleUpdateOne) check() error {
	if _, ok := uruo.mutation.UserEdgeID(); uruo.mutation.UserEdgeCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserRole.user_edge"`)
	}
	if _, ok := uruo.mutation.RoleEdgeID(); uruo.mutation.RoleEdgeCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserRole.role_edge"`)
	}
	return nil
}

func (uruo *UserRoleUpdateOne) sqlSave(ctx context.Context) (_node *UserRole, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userrole.Table,
			Columns: userrole.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: userrole.FieldID,
			},
		},
	}
	id, ok := uruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userrole.FieldID)
		for _, f := range fields {
			if !userrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uruo.mutation.UpdatedAt(); ok {
		_spec.SetField(userrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if uruo.mutation.UpdatedAtCleared() {
		_spec.ClearField(userrole.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := uruo.mutation.DeletedAt(); ok {
		_spec.SetField(userrole.FieldDeletedAt, field.TypeTime, value)
	}
	if uruo.mutation.DeletedAtCleared() {
		_spec.ClearField(userrole.FieldDeletedAt, field.TypeTime)
	}
	if uruo.mutation.UserEdgeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserEdgeTable,
			Columns: []string{userrole.UserEdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uruo.mutation.UserEdgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserEdgeTable,
			Columns: []string{userrole.UserEdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uruo.mutation.RoleEdgeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleEdgeTable,
			Columns: []string{userrole.RoleEdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: role.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uruo.mutation.RoleEdgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleEdgeTable,
			Columns: []string{userrole.RoleEdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: role.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserRole{config: uruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
